
services:
  db:
    container_name: "tours_dev"
    image: "postgres:16-alpine"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test_db:
    container_name: "tours_test"
    image: "postgres:16-alpine"
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpassword"
      POSTGRES_DB: "testdb"
    restart: unless-stopped
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
